logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: '%(asctime)s %(levelname)-1.1s %(process)d %(name)s:%(funcName)s:%(lineno)s
        | %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
  loggers:
    apscheduler:
      level: INFO
    pyemit:
      level: INFO
    werkzeug:
      level: WARNING
  root:
    handlers:
      - console
    level: INFO
redis:
  #dsn: redis://172.17.0.1:6379
  dsn: redis://192.168.100.101:56379
influxdb:
  url: http://192.168.100.101:58086
  token: hwxHycJfp_t6bCOYe2MhEDW4QBOO4FDtgeBWnPR6bGZJGEZ_41m_OHtTJFZKyD2HsbVqkZM8rJNkMvjyoXCG6Q==
  org: zillonare
  bucket_name: zillonare
  enable_compress: true
postgres:
  dsn: postgres://zillionare:123456@localhost:5432/zillionare
  enabled: false
alpha:
    data_home: ~/zillionare/alpha/data
    tts_server: http://127.0.0.1:5002/api/tts?
notify:
  mail_from: aaron_yang@jieyu.ai
  mail_to: aaron_yang@jieyu.ai
  mail_server: smtp.ym.163.com
backtest:
  url: http://192.168.100.114:7080/backtest/api/trade/v0.2/
  admin_token: bGZJGEZ
  commission: 1.5e-4
strategy:
    package_prefix: alpha.strategies
    source_dir: /apps/alpha/alpha/strategies
    exclude: ["base.py", "__init__.py"]
