
postgres:
  enabled: false

influxdb:
    url: http://192.168.100.101:38086
    token: 36DEKB4AMiiMjyT2enLKVonnmWSWNPhv7v3Dft5IQ6B2DLGGrUfmXEfLeyKIcPkHzT3N5jz1hKy4bpzOmrqGDg==
    org: my-org
    bucket_name: my-bucket
    enable_compress: true
